[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nonce_payment = "CwwpVy2fL2NoVYS1wZgvhfpumoCCQdmZd8194uKRpDo7"

[programs.localnet]
nonce_payment = "CwwpVy2fL2NoVYS1wZgvhfpumoCCQdmZd8194uKRpDo7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
